
noOfBackupWorkersPerGame=2
healthcheck.timeout=5000
healthcheck.interval=10000

workers=5

worker1.ip=localhost
worker1.port=8080
worker1.healthport=9080

worker2.ip=localhost
worker2.port=8081
worker2.healthport=9081

worker3.ip=localhost
worker3.port=8082
worker3.healthport=9082

worker4.ip=localhost
worker4.port=8083
worker4.healthport=9083

worker5.ip=localhost
worker5.port=8084
worker5.healthport=9084

master.ip=localhost
master.port=4321

reducer.ip=localhost
reducer.port=8900

srg.ip=localhost
srg.port=8000